// ---------------------------------------------------------------------------
// Mushaf
// ---------------------------------------------------------------------------
export type MushafCode = "v2";

export const MUSHAF_CODES: MushafCode[] = ["v2"];

/** Codes that use per-page QCF glyph fonts (not Unicode text) */
export const QCF_CODES: MushafCode[] = ["v2"];

export const MUSHAF_DISPLAY_NAMES: Record<MushafCode, string> = {
  v2: "V2",
};

export const MUSHAF_LINES: Record<MushafCode, number> = {
  v2: 15,
};

// ---------------------------------------------------------------------------
// Mushaf page data (matches the JSON generated by scripts/generate-mushaf-assets.ts)
// ---------------------------------------------------------------------------
export interface MushafWord {
  text: string;
  verseKey: string;
  x: number;
  width: number;
  charTypeName: string;
}

export interface MushafLine {
  lineNumber: number;
  centered?: boolean;
  words: MushafWord[];
}

export interface MushafPagePayload {
  page: number;
  mushafCode: string;
  lines: MushafLine[];
}

// ---------------------------------------------------------------------------
// Chapter metadata (from /chapters API)
// ---------------------------------------------------------------------------
export interface Chapter {
  id: number;
  nameSimple: string;
  nameArabic: string;
  versesCount: number;
  pages: [number, number]; // [startPage, endPage] in Madani mushaf
  revelationPlace: "makkah" | "madinah";
  bismillahPre: boolean;
}

// ---------------------------------------------------------------------------
// Translations
// ---------------------------------------------------------------------------
export type TranslationId = "saheeh" | "hilali-khan" | "abu-iyaad";
export const SUPPORTED_TRANSLATION_IDS = ["saheeh", "hilali-khan", "abu-iyaad"] as const satisfies readonly TranslationId[];

export type CopyVerseContentMode = "arabic" | "arabic-and-translations" | "translations";
export type AyahReciterId = "abdul-basit" | "husary" | "minshawi";
export type DataUsageMode = "low" | "balanced" | "high";

export const TRANSLATION_DISPLAY_NAMES: Record<TranslationId, string> = {
  saheeh: "Saheeh International",
  "hilali-khan": "Mohsin Khan and Taqi-ud-Din Hilali",
  "abu-iyaad": "Shaykh Abu Iyaad",
};

export const AYAH_RECITER_DISPLAY_NAMES: Record<AyahReciterId, string> = {
  "abdul-basit": "Abdul Basit Abdul Samad",
  husary: "Mahmoud Khalil al-Husary",
  minshawi: "Muhammad Siddiq al-Minshawi",
};

export const AYAH_RECITER_AUDIO_PATHS: Record<AyahReciterId, string> = {
  "abdul-basit": "abdulBasitMurattal",
  husary: "husary",
  minshawi: "minshawyMurattal",
};

export const SUPPORTED_AYAH_RECITERS = [
  "abdul-basit",
  "husary",
  "minshawi",
] as const satisfies readonly AyahReciterId[];

/** Maps our internal translation ID to the api.quran.com resource ID */
export const TRANSLATION_API_IDS: Record<Exclude<TranslationId, "abu-iyaad">, number> = {
  saheeh: 20,
  "hilali-khan": 203,
};

export interface TranslationEntry {
  verseKey: string;
  text: string;
}

// ---------------------------------------------------------------------------
// Themes
// ---------------------------------------------------------------------------
export type ThemeId =
  | "light-warm"
  | "dark-warm"
  | "white-green"
  | "classic-dark"
  | "blue-slate-dark"
  | "blue-slate-light";

export interface ThemeColors {
  bg: string;
  text: string;
  accent: string;
  surface: string;
  muted: string;
}

export const THEMES: Record<ThemeId, { label: string; colors: ThemeColors; pair?: ThemeId }> = {
  "light-warm": {
    label: "Warm Light",
    colors: { bg: "#f7f1e4", text: "#2c2c2c", accent: "#8b6914", surface: "#efe8d6", muted: "#756548" },
    pair: "dark-warm",
  },
  "dark-warm": {
    label: "Warm Dark",
    colors: { bg: "#1a1410", text: "#e8dcc8", accent: "#c4a35a", surface: "#2a2218", muted: "#9b8b70" },
    pair: "light-warm",
  },
  "white-green": {
    label: "Classic Light",
    colors: { bg: "#ffffff", text: "#1a1a1a", accent: "#2d6a4f", surface: "#f0f5f0", muted: "#567362" },
    pair: "classic-dark",
  },
  "classic-dark": {
    label: "Classic Dark",
    colors: { bg: "#0d1f17", text: "#e0ebe5", accent: "#5fa87f", surface: "#152b21", muted: "#7a9b8a" },
    pair: "white-green",
  },
  "blue-slate-dark": {
    label: "Slate Dark",
    colors: { bg: "#0f1724", text: "#e6edf7", accent: "#7aa2f7", surface: "#1b2535", muted: "#93a2ba" },
    pair: "blue-slate-light",
  },
  "blue-slate-light": {
    label: "Slate Light",
    colors: { bg: "#f4f7fb", text: "#1f2937", accent: "#345caa", surface: "#e7edf6", muted: "#586a84" },
    pair: "blue-slate-dark",
  },
};

// ---------------------------------------------------------------------------
// Reading mode
// ---------------------------------------------------------------------------
export type ReadingMode = "swipe" | "scroll";
export type ViewMode = "mushaf" | "vbv" | "scroll";
export type VbvSubmode = "s" | "j" | "p";

// ---------------------------------------------------------------------------
// User preferences (persisted to localStorage)
// ---------------------------------------------------------------------------
export interface UserPreferences {
  mushafCode: MushafCode;
  translationIds: TranslationId[];
  dataUsageMode: DataUsageMode;
  copyVerseContentMode: CopyVerseContentMode;
  copyTranslationIds: TranslationId[];
  ayahReciterId: AyahReciterId;
  inlineVerseNotes: boolean;
  theme: ThemeId;
  fontScale: number; // 1-10
  viewMode: ViewMode;
  vbvSubmode: VbvSubmode;
  scrollSubmode: VbvSubmode;
}

export const DEFAULT_PREFERENCES: UserPreferences = {
  mushafCode: "v2",
  translationIds: ["saheeh", "abu-iyaad"],
  dataUsageMode: "balanced",
  copyVerseContentMode: "arabic-and-translations",
  copyTranslationIds: ["saheeh", "abu-iyaad"],
  ayahReciterId: "abdul-basit",
  inlineVerseNotes: false,
  theme: "light-warm",
  fontScale: 1,
  viewMode: "mushaf",
  vbvSubmode: "s",
  scrollSubmode: "p",
};

// ---------------------------------------------------------------------------
// Reading history
// ---------------------------------------------------------------------------
export interface HistoryEntry {
  chapterId: number;
  chapterName: string;
  verseKey: string;
  pageNumber: number;
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Offline / download status
// ---------------------------------------------------------------------------
export interface DownloadProgress {
  total: number;
  done: number;
  label: string;
}

export interface OfflineStatus {
  online: boolean;
  downloadedMushafs: MushafCode[];
  downloadedTranslations: TranslationId[];
}

// ---------------------------------------------------------------------------
// Audio
// ---------------------------------------------------------------------------
export interface AudioFile {
  chapterId: number;
  url: string;
  fileSize: number;
}
