// ---------------------------------------------------------------------------
// Mushaf
// ---------------------------------------------------------------------------
export type MushafCode = "v2";

export const MUSHAF_CODES: MushafCode[] = ["v2"];

/** Codes that use per-page QCF glyph fonts (not Unicode text) */
export const QCF_CODES: MushafCode[] = ["v2"];

export const MUSHAF_DISPLAY_NAMES: Record<MushafCode, string> = {
  v2: "V2",
};

export const MUSHAF_LINES: Record<MushafCode, number> = {
  v2: 15,
};

// ---------------------------------------------------------------------------
// Mushaf page data (matches the JSON generated by scripts/generate-mushaf-assets.ts)
// ---------------------------------------------------------------------------
export interface MushafWord {
  text: string;
  verseKey: string;
  x: number;
  width: number;
  charTypeName: string;
}

export interface MushafLine {
  lineNumber: number;
  centered?: boolean;
  words: MushafWord[];
}

export interface MushafPagePayload {
  page: number;
  mushafCode: string;
  lines: MushafLine[];
}

// ---------------------------------------------------------------------------
// Chapter metadata (from /chapters API)
// ---------------------------------------------------------------------------
export interface Chapter {
  id: number;
  nameSimple: string;
  nameArabic: string;
  versesCount: number;
  pages: [number, number]; // [startPage, endPage] in Madani mushaf
  revelationPlace: "makkah" | "madinah";
  bismillahPre: boolean;
}

// ---------------------------------------------------------------------------
// Translations
// ---------------------------------------------------------------------------
export type TranslationId = "saheeh" | "hilali-khan" | "abu-iyaad";
export const SUPPORTED_TRANSLATION_IDS = ["saheeh", "hilali-khan", "abu-iyaad"] as const satisfies readonly TranslationId[];

export type CopyVerseContentMode = "arabic" | "arabic-and-translations" | "translations";
export type AyahReciterId = "abdul-basit" | "husary" | "minshawi";

export const TRANSLATION_DISPLAY_NAMES: Record<TranslationId, string> = {
  saheeh: "Saheeh International",
  "hilali-khan": "Mohsin Khan and Taqi-ud-Din Hilali",
  "abu-iyaad": "Abu Iyaad",
};

export const AYAH_RECITER_DISPLAY_NAMES: Record<AyahReciterId, string> = {
  "abdul-basit": "Abdul Basit Abdul Samad",
  husary: "Mahmoud Khalil al-Husary",
  minshawi: "Muhammad Siddiq al-Minshawi",
};

export const AYAH_RECITER_DATA_FILES: Record<AyahReciterId, string> = {
  "abdul-basit": "ayah-recitation-abdul-basit-abdul-samad-murattal-hafs-950.json",
  husary: "ayah-recitation-mahmoud-khalil-al-husary-murattal-hafs-957.json",
  minshawi: "ayah-recitation-muhammad-siddiq-al-minshawi-murattal-hafs-959.json",
};

export const SUPPORTED_AYAH_RECITERS = [
  "abdul-basit",
  "husary",
  "minshawi",
] as const satisfies readonly AyahReciterId[];

/** Maps our internal translation ID to the api.quran.com resource ID */
export const TRANSLATION_API_IDS: Record<Exclude<TranslationId, "abu-iyaad">, number> = {
  saheeh: 20,
  "hilali-khan": 203,
};

export interface TranslationEntry {
  verseKey: string;
  text: string;
}

// ---------------------------------------------------------------------------
// Themes
// ---------------------------------------------------------------------------
export type ThemeId = "light-warm" | "dark-warm" | "white-green";

export interface ThemeColors {
  bg: string;
  text: string;
  accent: string;
  surface: string;
  muted: string;
}

export const THEMES: Record<ThemeId, { label: string; colors: ThemeColors }> = {
  "light-warm": {
    label: "Light",
    colors: { bg: "#f7f1e4", text: "#2c2c2c", accent: "#8b6914", surface: "#efe8d6", muted: "#a09070" },
  },
  "dark-warm": {
    label: "Dark",
    colors: { bg: "#1a1410", text: "#e8dcc8", accent: "#c4a35a", surface: "#2a2218", muted: "#7a6a50" },
  },
  "white-green": {
    label: "Classic",
    colors: { bg: "#ffffff", text: "#1a1a1a", accent: "#2d6a4f", surface: "#f0f5f0", muted: "#6b8f7b" },
  },
};

// ---------------------------------------------------------------------------
// Reading mode
// ---------------------------------------------------------------------------
export type ReadingMode = "swipe" | "scroll";
export type ViewMode = "mushaf" | "vbv" | "scroll";
export type VbvSubmode = "s" | "j" | "p";

// ---------------------------------------------------------------------------
// User preferences (persisted to localStorage)
// ---------------------------------------------------------------------------
export interface UserPreferences {
  mushafCode: MushafCode;
  translationIds: TranslationId[];
  copyVerseContentMode: CopyVerseContentMode;
  copyTranslationIds: TranslationId[];
  ayahReciterId: AyahReciterId;
  inlineVerseNotes: boolean;
  theme: ThemeId;
  fontScale: number; // 1-10
  viewMode: ViewMode;
  vbvSubmode: VbvSubmode;
  scrollSubmode: VbvSubmode;
}

export const DEFAULT_PREFERENCES: UserPreferences = {
  mushafCode: "v2",
  translationIds: ["saheeh", "abu-iyaad"],
  copyVerseContentMode: "arabic-and-translations",
  copyTranslationIds: ["saheeh", "abu-iyaad"],
  ayahReciterId: "abdul-basit",
  inlineVerseNotes: false,
  theme: "light-warm",
  fontScale: 1,
  viewMode: "mushaf",
  vbvSubmode: "s",
  scrollSubmode: "p",
};

// ---------------------------------------------------------------------------
// Reading history
// ---------------------------------------------------------------------------
export interface HistoryEntry {
  chapterId: number;
  chapterName: string;
  verseKey: string;
  pageNumber: number;
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Offline / download status
// ---------------------------------------------------------------------------
export interface DownloadProgress {
  total: number;
  done: number;
  label: string;
}

export interface OfflineStatus {
  online: boolean;
  downloadedMushafs: MushafCode[];
  downloadedTranslations: TranslationId[];
}

// ---------------------------------------------------------------------------
// Audio
// ---------------------------------------------------------------------------
export interface AudioFile {
  chapterId: number;
  url: string;
  fileSize: number;
}
