import { SEARCH_INDEX_VERSION } from "./format";

/**
 * Public URL of the precomputed search index (generated by scripts/generate-search-index.ts).
 * The version query defeats the service worker's cache-first strategy when the format changes.
 */
export const SEARCH_INDEX_URL = `/data/search-index.bin?v=${SEARCH_INDEX_VERSION}`;
/** Path of the index relative to the repo root (server-side reads). */
export const SEARCH_INDEX_FILE = "public/data/search-index.bin";
/** IndexedDB store + key holding the downloaded index (see src/lib/offline/storage.ts). */
export const SEARCH_INDEX_STORE = "search-index";
export const SEARCH_INDEX_KEY = `v${SEARCH_INDEX_VERSION}`;
/** Keys of older formats that may still sit in IndexedDB from earlier downloads. */
export const SEARCH_INDEX_LEGACY_KEYS: readonly string[] = ["v1"];

export const SEARCH_DEFAULT_LIMIT = 30;
export const SEARCH_MAX_LIMIT = 500;
/** Minimum number of letters (after normalization, spaces excluded) before the UI runs a search. */
export const SEARCH_MIN_QUERY_LETTERS = 3;
export const SEARCH_EMPTY_QUERY_ERROR = "query became empty after normalization";
