/** Public URL of the precomputed search index (generated by scripts/generate-search-index.ts). */
export const SEARCH_INDEX_URL = "/data/search-index.bin";
/** Path of the index relative to the repo root (server-side reads). */
export const SEARCH_INDEX_FILE = "public/data/search-index.bin";
/** IndexedDB store + key holding the downloaded index (see src/lib/offline/storage.ts). */
export const SEARCH_INDEX_STORE = "search-index";
export const SEARCH_INDEX_KEY = "v1";

export const SEARCH_DEFAULT_LIMIT = 30;
export const SEARCH_MAX_LIMIT = 500;
export const SEARCH_EMPTY_QUERY_ERROR = "query became empty after normalization";
