import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";

async function main() {
    const dataPath = join(process.cwd(), "public", "data", "abu-iyaad.json");
    const destPath = join(process.cwd(), "src", "lib", "translations", "abuIyaadKeys.ts");

    let keys: string[] = [];

    if (existsSync(dataPath)) {
        console.log(`Found abu-iyaad.json across ${dataPath}. Extracting keys...`);
        const content = await readFile(dataPath, "utf-8");
        const json = JSON.parse(content);
        keys = Object.keys(json);
    } else {
        console.warn(`⚠️ Warning: abu-iyaad.json not found at public/data/abu-iyaad.json.`);
        console.warn(`Generating an empty Set. Please add the file and re-run this script.`);
    }

    const fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/generate-abu-iyaad-keys.ts

export const ABU_IYAAD_KEYS = new Set<string>([
  ${keys.map((k) => `"${k}"`).join(",\n  ")}
]);
`;

    await writeFile(destPath, fileContent, "utf-8");
    console.log(`Successfully generated src/lib/translations/abuIyaadKeys.ts with ${keys.length} keys.`);
}

main().catch(console.error);
